#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
START=24
STOP=11
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/handheld-controls
	procd_set_param respawn 3600 3 5
	procd_set_param term_timeout 10
	procd_set_param stderr 1
	procd_close_instance
}
