#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
START=25
STOP=10
USE_PROCD=1

start_service() {
	[ "$(uci -q get handheld.frontend.enabled)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/bin/emulationstation-session
	procd_set_param respawn 3600 3 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 10
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger handheld
}
